### ISSUE TITLE
Edit default branch for some apps

### ISSUE THREAD

**Issue by szaimen** [szaimen/nextcloud-easy-test#11]
https://github.com/nextcloud/groupware/issues/3

**Comment by miaulalala** [comment]
All Groupware branches have been renamed FYI

**Comment by szaimen** [comment]
Thanks for letting me know!

**Comment by szaimen** [comment]
fixed with https://github.com/szaimen/nextcloud-easy-test/commit/7f99ef475599d2b6a502b1f5a394c528ac561868
