### ISSUE TITLE
ARM64 image

### ISSUE THREAD

**Issue by SystemKeeper** [szaimen/nextcloud-easy-test#20]
Hey,

the image from Julius (ghcr.io/juliushaertl/nextcloud-dev-php74) is available for amd64 and for arm64. Any chance arm64 can be made available for nextcloud-easy-test as well? Of course building the image locally is also an option.

**Comment by szaimen** [comment]
Implemented with https://github.com/szaimen/nextcloud-easy-test/commit/6dddfaac44727a999d38ea4c64042de68cd1cd3e
