### ISSUE TITLE
Upgrade to PHP 8

### ISSUE THREAD

**Issue by SystemKeeper** [szaimen/nextcloud-easy-test#24]
PHP 7.4 support will be dropped with NC 26. The PR https://github.com/nextcloud/server/pull/36069 already uses PHP 8 specific features (`mixed`), resulting in:
```
 - Initialize migration of background images from dashboard to theming app
PHP Fatal error:  Declaration of OCA\Theming\Jobs\MigrateBackgroundImages::run(OCA\Theming\Jobs\mixed $argument): void must be compatible with OCP\BackgroundJob\Job::run($argument) in /var/www/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php on line 71
```

So guess the images here need to be upgraded to PHP 8 as well :-)

**Comment by szaimen** [comment]
Fixed with https://github.com/szaimen/nextcloud-easy-test/commit/433d33424d8b3e9d77c77fe20e67016e38c33fff and the image was updated.
