### ISSUE TITLE
Errorlog in nextcloud-easy-test?

### ISSUE THREAD

**Issue by SystemKeeper** [szaimen/nextcloud-easy-test#31]
Usually exceptions won't be logged when running nextcloud-easy-test. I tend to always execute
```
occ config:system:set log_type --value "errorlog"
```
to see errors. Am I missing something here or would it make sense to add this to `remote.sh`?

**Comment by szaimen** [comment]
Added with https://github.com/szaimen/nextcloud-easy-test/commit/24d8608cf1b8e61341764f2b5331d2688cc65321
