### ISSUE TITLE
Ability to easily test full standard release setup

### ISSUE THREAD

**Issue by jancborchardt** [szaimen/nextcloud-easy-test#40]
First off thanks again for this amazing tool @szaimen, definitely deserves the name "easy". :)

As mentioned, one thing I would love is a quick copy & paste command which includes all the apps in a regular release so we can test as closely as possible to a release, something easily copy-able from the readme.
Probably just a matter of taking most of the easy copy paste list of the apps down there? Or could be a variable even so it’s always up to date and not a huge copypaste command.

**Comment by szaimen** [comment]
Done. See 
![image](https://github.com/szaimen/nextcloud-easy-test/assets/42591237/90b9be26-1699-43d6-aeff-35c37e55d949)

**Comment by szaimen** [comment]
One example:
```bash
docker run -it \
-e FULL_INSTANCE_BRANCH=stable28 \
--name nextcloud-easy-test \
-p 127.0.0.1:8443:443 \
--volume="nextcloud_easy_test_npm_cache_volume:/var/www/.npm" \
ghcr.io/szaimen/nextcloud-easy-test:latest
```
